# Generated by Django 3.2.24 on 2024-05-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttle', models.CharField(max_length=50)),
                ('distribution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distribution', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttle', models.CharField(max_length=50)),
                ('mail', models.EmailField(help_text='Enter Your Company Email for Contact with YOUR Web Visitor', max_length=254)),
                ('tel', models.BigIntegerField(help_text='Enter Your Company Phone Number for Contact with YOUR Web Visitor')),
                ('address', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Txt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=150)),
                ('distribution', models.TextField()),
                ('time', models.DateTimeField()),
                ('special', models.BooleanField(blank=True, null=True)),
                ('categorry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesco.category')),
            ],
        ),
    ]
