# Generated by Django 4.2.13 on 2024-06-11 08:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("tesco", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="txt", name="distribution", field=tinymce.models.HTMLField(),
        ),
    ]
